export const users = [
  {
    name: "Mira Patel",
    email: "mira@campus.edu",
    password: "password123",
    collegeId: "STU2301",
    campus: "Ahmedabad Design Campus",
    location: "Girls Hostel Block A",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    role: "student",
    balance: 5000,
  },
  {
    name: "Aiden Thomas",
    email: "aiden@campus.edu",
    password: "password123",
    collegeId: "STU2302",
    campus: "Ahmedabad Design Campus",
    location: "North Academic Gate",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    role: "seller",
    balance: 2000,
  },
  {
    name: "Neha Sharma",
    email: "neha@campus.edu",
    password: "password123",
    collegeId: "STU2303",
    campus: "Ahmedabad Design Campus",
    location: "Library Square",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80",
    role: "poc",
    balance: 500,
  },
  {
    name: "Rohan Verma",
    email: "rented4us@gmail.com",
    password: "RentED@123",
    collegeId: "STU2304",
    campus: "City Science College",
    location: "City Center",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80",
    role: "admin",
    balance: 0,
  },
];

export const items = [
  {
    ownerEmail: "aiden@campus.edu",
    title: "Engineering Mathematics Textbook",
    description: "Clean copy with highlighted formula sheets for first-year engineering students.",
    listingType: "both",
    rentalPrice: 80,
    salePrice: 320,
    category: "Engineering Books",
    location: "Girls Hostel Block A",
    campus: "Ahmedabad Design Campus",
    condition: "Good",
    brand: "Cengage",
    details: ["Highlighted formulas included", "No torn pages", "Useful for first-year engineering"],
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=500&q=80",
    photos: ["https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=500&q=80", "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=500&q=80"],
    tags: ["maths", "semester 1", "textbook"],
  },
  {
    ownerEmail: "aiden@campus.edu",
    title: "Casio Scientific Calculator fx-991ES",
    description: "Perfect for exams and lab calculations. Comes with cover and extra battery.",
    listingType: "both",
    rentalPrice: 40,
    salePrice: 650,
    category: "Calculators",
    location: "North Academic Gate",
    campus: "Ahmedabad Design Campus",
    condition: "Like New",
    brand: "Casio",
    details: ["Original cover included", "Buttons working perfectly", "Good for exams and labs"],
    image: "https://images.unsplash.com/photo-1574634534894-89d7576c8259?auto=format&fit=crop&w=500&q=80",
    photos: ["https://images.unsplash.com/photo-1574634534894-89d7576c8259?auto=format&fit=crop&w=500&q=80", "https://images.unsplash.com/photo-1583508915901-b5f84c1dcde1?auto=format&fit=crop&w=500&q=80"],
    tags: ["calculator", "exam", "electronics"],
  },
  {
    ownerEmail: "aiden@campus.edu",
    title: "Shared PG Room Near Library",
    description: "Furnished room with Wi-Fi, laundry access, and 5-minute walk to campus.",
    listingType: "both",
    rentalPrice: 450,
    salePrice: 18000,
    category: "Room / PG Listings",
    location: "Library Square",
    campus: "Ahmedabad Design Campus",
    condition: "Good",
    brand: "Hostel Furnished",
    details: ["Wi-Fi included", "Laundry access nearby", "Walkable to campus"],
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=500&q=80",
    photos: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=500&q=80", "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=500&q=80", "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=500&q=80"],
    tags: ["pg", "room", "wifi"],
  },
  {
    ownerEmail: "aiden@campus.edu",
    title: "Organic Chemistry Lab Kit",
    description: "Temporary kit for lab sessions with goggles, droppers, and measuring tubes.",
    listingType: "both",
    rentalPrice: 70,
    salePrice: 540,
    category: "Lab Equipment",
    location: "Girls Hostel Block A",
    campus: "Ahmedabad Design Campus",
    condition: "Good",
    brand: "Lab Essentials",
    details: ["Includes goggles and droppers", "Suitable for chemistry practicals", "Easy to carry"],
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=500&q=80",
    photos: ["https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=500&q=80", "https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=500&q=80"],
    tags: ["lab", "chemistry", "kit"],
  },
  {
    ownerEmail: "aiden@campus.edu",
    title: "Data Structures Handbook",
    description: "Useful quick-reference book for coding interviews and semester revision.",
    listingType: "both",
    rentalPrice: 60,
    salePrice: 240,
    category: "Books",
    location: "City Center",
    campus: "City Science College",
    condition: "Fair",
    brand: "Technical Press",
    details: ["Useful for interview revision", "Readable copy", "Some handwritten notes inside"],
    image: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=500&q=80",
    photos: ["https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=500&q=80", "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=500&q=80"],
    tags: ["coding", "cs", "revision"],
  },
  {
    ownerEmail: "aiden@campus.edu",
    title: "Drafting Board for Architecture Studio",
    description: "A2 drafting board with clips and carry strap for studio projects.",
    listingType: "both",
    rentalPrice: 90,
    salePrice: 1100,
    category: "Lab Equipment",
    location: "Library Square",
    campus: "Ahmedabad Design Campus",
    condition: "Like New",
    brand: "StudioDraft",
    details: ["Carry strap included", "Strong clips", "Good for architecture submissions"],
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=500&q=80",
    photos: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=500&q=80"],
    tags: ["architecture", "studio", "drafting"],
  },
  {
    ownerEmail: "aiden@campus.edu",
    title: "Student Laptop for Coding Labs",
    description: "14-inch laptop with charger, webcam, and enough battery life for coding classes and presentations.",
    listingType: "both",
    rentalPrice: 220,
    salePrice: 26500,
    category: "Electronics",
    location: "Innovation Block C",
    campus: "Ahmedabad Design Campus",
    condition: "Good",
    brand: "Dell Inspiron",
    details: ["Charger included", "Good for coding and online classes", "Battery backup around 4 hours"],
    image: "https://images.unsplash.com/photo-1496181130204-755241524eab?auto=format&fit=crop&w=500&q=80",
    photos: ["https://images.unsplash.com/photo-1496181130204-755241524eab?auto=format&fit=crop&w=500&q=80"],
    tags: ["laptop", "coding", "assignments"],
  },
  {
    ownerEmail: "aiden@campus.edu",
    title: "Biology Practical Kit Set",
    description: "Complete biology kit with slides, droppers, forceps, gloves, and storage pouch for practical sessions.",
    listingType: "both",
    rentalPrice: 85,
    salePrice: 780,
    category: "Lab Equipment",
    location: "City Science College Lab Wing",
    campus: "City Science College",
    condition: "Like New",
    brand: "BioLab Essentials",
    details: ["Slides and forceps included", "Useful for first-year biology labs", "Clean pouch with labeled sections"],
    image: "https://images.unsplash.com/photo-1530210124550-912dc1381cb8?auto=format&fit=crop&w=500&q=80",
    photos: ["https://images.unsplash.com/photo-1530210124550-912dc1381cb8?auto=format&fit=crop&w=500&q=80"],
    tags: ["biology", "practical", "lab"],
  },
  {
    ownerEmail: "aiden@campus.edu",
    title: "Single Study Room Near Campus Gate",
    description: "Quiet single room with study table, fan, attached washroom, and quick access to the main campus road.",
    listingType: "both",
    rentalPrice: 520,
    salePrice: 16500,
    category: "Room / PG Listings",
    location: "East Gate Residency",
    campus: "Ahmedabad Design Campus",
    condition: "Like New",
    brand: "Student Stay",
    details: ["Study table and wardrobe included", "Attached washroom", "Ideal for exam-season focus"],
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=500&q=80",
    photos: ["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=500&q=80"],
    tags: ["single room", "study", "attached washroom"],
  },
];

export const rentalRequests = [
  {
    itemTitle: "Casio Scientific Calculator fx-991ES",
    renterEmail: "mira@campus.edu",
    startDate: "2026-07-06",
    endDate: "2026-07-12",
    message: "Need this for my semester exams.",
    status: "Payment Successful",
    totalPrice: 240,
    dummyPaymentStatus: "captured",
    dummyPaymentReference: "REF-1001",
    deliveryAddress: "Girls Hostel Block A",
    pickupQrCode: "P-123456",
    deliveryQrCode: "D-654321",
    trackingStatus: "Payment Successful",
  },
  {
    itemTitle: "Shared PG Room Near Library",
    renterEmail: "mira@campus.edu",
    startDate: "2026-07-10",
    endDate: "2026-08-10",
    message: "Booking a PG room for my summer internship.",
    status: "Payment Successful",
    totalPrice: 13500,
    dummyPaymentStatus: "cod_pending",
    dummyPaymentReference: "COD-1002",
    deliveryAddress: "Library Square",
    pickupQrCode: "P-789012",
    deliveryQrCode: "D-210987",
    trackingStatus: "Payment Successful",
  },
];

export const conversations = [
  {
    itemTitle: "Casio Scientific Calculator fx-991ES",
    participantEmails: ["mira@campus.edu", "aiden@campus.edu"],
    messages: [
      { senderEmail: "mira@campus.edu", text: "Hi, is the calculator still available for next week?" },
      { senderEmail: "aiden@campus.edu", text: "Yes, it is. You can place an order for your quiz dates." },
    ],
  },
];

export const reviews = [
  {
    itemTitle: "Casio Scientific Calculator fx-991ES",
    reviewerEmail: "mira@campus.edu",
    revieweeEmail: "aiden@campus.edu",
    rating: 5,
    comment: "Very responsive and the calculator was exactly as described.",
  },
];
